[package]
name = "pngme"
version = "0.1.0"
edition = "2021"
about = "manipulate, encode and decode png files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
crc = "3.2.1"
